# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c8ad728d9d11b8ce74ae44883ba10cb531e3d3901d3d287d2447ce2c47471b60bf4b619ba912290c8f240023036f986f77603b3dece01af1fad330fbfb46759
  consumer_key: tFQK4ikqpz6IPdQQYpFwlZGOg
  consumer_secret: melslYXtpawIVcx226pYLJcMJIDlNOFcNG6ozV0CM9pWKAUrBm
  access_token: 3745695433-XAl9Tjd4GAacLcIaiLuUA60sKFyGnE6MWPNjDbI
  access_token_secret: XiS9lcIVGD7YeghdM37UbLbxQ91LKgSXtWvJBz8jaDP3Y

test:
  secret_key_base: 6abac339e7490f760d23e8eb6770be7434e060f464a1a5559eae399aa481981ef33902d01d3d2404f51352bdfb3c241e5bd5e8201a5792768b0f90eac5517fb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  consumer_key: tFQK4ikqpz6IPdQQYpFwlZGOg
  consumer_secret: melslYXtpawIVcx226pYLJcMJIDlNOFcNG6ozV0CM9pWKAUrBm
  access_token: 3745695433-XAl9Tjd4GAacLcIaiLuUA60sKFyGnE6MWPNjDbI
  access_token_secret: XiS9lcIVGD7YeghdM37UbLbxQ91LKgSXtWvJBz8jaDP3Y

#twitter_api_key: tFQK4ikqpz6IPdQQYpFwlZGOg
#twitter_api_secret: melslYXtpawIVcx226pYLJcMJIDlNOFcNG6ozV0CM9pWKAUrBm